// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID        string   `json:"id"`
	Post      *Post    `json:"post"`
	Author    *User    `json:"author"`
	Parent    *Comment `json:"parent,omitempty"`
	Content   string   `json:"content"`
	CreatedAt string   `json:"createdAt"`
}

type Mutation struct {
}

type Post struct {
	ID              string     `json:"id"`
	Title           string     `json:"title"`
	Content         string     `json:"content"`
	Author          *User      `json:"author"`
	DisableComments bool       `json:"disableComments"`
	CreatedAt       string     `json:"createdAt"`
	Comments        []*Comment `json:"comments"`
}

type Query struct {
}

type Subscription struct {
}

type User struct {
	ID        string `json:"id"`
	Username  string `json:"username"`
	CreatedAt string `json:"createdAt"`
}
